spring:
  datasource:
    url: jdbc:mysql://47.89.9.216:3306/source_item_one?useUnicode=true&characterEncoding=UTF-8&&useSSL=false&&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:static/,file:static/
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8082
